version: "2"

services:
  gateway-rs:
    build: ./gateway-rs
    devices:
      - /dev/i2c-1
    expose:
      - "1680"
    environment:
      - GATEWAY_SETTINGS=/app/settings.toml
    depends_on:
      - packet-forwarder
    network_mode: host

  packet-forwarder:
    # Use pre-defined image
    image: rakwireless/udp-packet-forwarder:latest
    restart: unless-stopped
    privileged: true # set this to true or define the required devices to share with the container under the `devices` tag below
    network_mode: host # required to read host interface MAC instead of virtual one, you don't need this if you set the GATEWAY_EUI manually

    environment:
      MODEL: "RAK7248"

      USE_LIBGPIOD: 1
      RESET_GPIO: 25
      # Each gateway is identified by its Gateway EUI (8 bytes in hex format)
      # The procedure to defined that EUI is as follows:
      # 1) It will use the EUI in the configuration files provided if any
      # 2) It will use the concentrator Chip ID if GATEWAY_EUI_SOURCE set to "chip" (will work only for Corecell concentrators)
      # 3) It will use the GATEWAY_EUI variable below if defined
      # 4) It will use the MAC address of the network interface identified by GATEWAY_EUI_SOURCE
      # 5) It will use the MAC address of the first existing network interface in this list: eth0, wlan0 and usb0
      # 6) It will use the MAC address of the network interface with more traffic
      # For options 4 to 6 you want to use network mode host to get the same EUI accross container reboots
      #GATEWAY_EUI_SOURCE: "enx00e04c68160f"
      #GATEWAY_EUI_SOURCE: "chip"
      #GATEWAY_EUI: "00E04CFFFE68160F"

      # Helium settings
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 1680

